# Generated by Django 5.2.8 on 2025-12-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_cart_cartitem_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_ptr',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_old',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
