# Generated by Django 5.2.8 on 2025-12-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_category_ptr_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
