# Generated by Django 5.2.8 on 2025-12-31 10:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_eco_packaging_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_type',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI / Digital Wallet'), ('crypto', 'Cryptocurrency'), ('bnpl', 'Buy Now, Pay Later')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='carbon_footprint',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='kg CO2 per unit', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='login.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='eco_packaging_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_eco_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sustainability_score',
            field=models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.JSONField(blank=True, default=list, help_text='List of earned badges'),
        ),
        migrations.AddField(
            model_name='profile',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to video testimonial (e.g., TikTok/Instagram/YouTube)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, default='Uncategorized', max_length=50),
        ),
    ]
